version: '3.9'

services:
  # API Gateway Service
  gateway_service:
    build:
      context: ./gateway_service
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=your-secret-key-change-in-production
      - DB_HOST=postgres
      - DB_NAME=dian_saas
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_PORT=5432
      - EXCEL_SERVICE_URL=http://excel_service:8001
      - PDF_SERVICE_URL=http://pdf_service:8002
      - DIAN_SERVICE_URL=http://dian_processing_service:8003
    depends_on:
      - postgres
      - excel_service
      - pdf_service
      - dian_processing_service

  # Excel Service
  excel_service:
    build:
      context: ./excel_service
    ports:
      - "8001:8001"
    environment:
      - JWT_SECRET=your-secret-key-change-in-production
      - DB_HOST=postgres
      - DB_NAME=dian_saas
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_PORT=5432
    depends_on:
      - postgres
    volumes:
      - excel_temp:/app/temp_excel

  # PDF Service
  pdf_service:
    build:
      context: ./pdf_service
    ports:
      - "8002:8002"
    environment:
      - JWT_SECRET=your-secret-key-change-in-production
      - DB_HOST=postgres
      - DB_NAME=dian_saas
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_PORT=5432
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-your_access_key}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-your_secret_key}
      - S3_BUCKET=${S3_BUCKET:-dian-pdf-reports}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    depends_on:
      - postgres
    volumes:
      - pdf_temp:/app/pdfs

  # DIAN Processing Service
  dian_processing_service:
    build:
      context: ./dian_processing_service
    ports:
      - "8003:8003"
    environment:
      - JWT_SECRET=your-secret-key-change-in-production
      - DB_HOST=postgres
      - DB_NAME=dian_saas
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_PORT=5432
    depends_on:
      - postgres
    volumes:
      - dian_reports:/app/dian_reports

  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dian_saas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dian_saas"]
      interval: 10s
      timeout: 5s
      retries: 5

  # React Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway_service
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Optional: S3 Mock for development
  s3_mock:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - s3_data:/data
    profiles:
      - s3-mock

volumes:
  pgdata:
  excel_temp:
  pdf_temp:
  dian_reports:
  s3_data:
