services:
  - type: web
    name: dian-processing-service
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        value: your-postgres-host
      - key: DB_NAME
        value: dian_saas
      - key: DB_USER
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 8003 